/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2019-10-16 12:40:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class idCheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"main.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Righteous&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Gothic+A1|Righteous&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".logo{\r\n");
      out.write("\r\n");
      out.write("font-family:righteous,serif;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("margin-left:auto;\r\n");
      out.write("margin-right:auto;\r\n");
      out.write("margin-top:auto;\r\n");
      out.write("margin-botton:auto;\r\n");
      out.write("}\r\n");
      out.write("tr td input.fix{\r\n");
      out.write("\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\tbackground:#333333;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tpadding:3px 8px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>ID 중복검사</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"idCheck.do\" method=\"post\" name=\"f\">\r\n");
      out.write("\t<table align=\"center\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<th colspan=\"2\" style=\"padding-left: 60px;\"><a href=\"mainPage.do\" >\r\n");
      out.write("\t\t\t<font class=\"logo\" color=\"red\" size=\"15px\">You</font>\r\n");
      out.write("\t\t\t<font class=\"logo\" color=\"black\" size=\"15px\">Sub</font>\r\n");
      out.write("\t\t</a></th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td align=\"center\">\r\n");
      out.write("\t\t<input type=\"text\" name=\"id\" value=\"");
      out.print(request.getParameter("id") );
      out.write("\" >\r\n");
      out.write("\t\t<input type=\"submit\" value=\"ID 중복 확인\">\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td align=\"center\" class=\"checkedId\" colspan=\"2\">\r\n");
      out.write("\t");
if(request.getAttribute("checkId")!=null){ 
	
	
      out.write("\r\n");
      out.write("\t<p> ");
      out.print(request.getAttribute("checkId") );
      out.write("&nbsp;&nbsp;<input type=\"button\" onclick=\"window.close()\" value=\"사용하기\" class=\"fix\" ></p>\r\n");
      out.write("\t");

	
	}else{
      out.write("\r\n");
      out.write("\t\t<p>해당아이디를 사용할수 없습니다<p>\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><p id=\"check\"></p></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
