/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2019-10-16 12:40:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"main.css\">\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Righteous&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Gothic+A1|Righteous&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".logo{\r\n");
      out.write("\r\n");
      out.write("font-family:righteous,serif;\r\n");
      out.write("}\r\n");
      out.write(".kor{\r\n");
      out.write("font-family:\"Gothic A1\",serif;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("margin-left:auto;\r\n");
      out.write("margin-right:auto;\r\n");
      out.write("margin-top:auto;\r\n");
      out.write("\r\n");
      out.write("margin-botton:auto;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("tr td button.sign{\r\n");
      out.write("\r\n");
      out.write("\tborder:1px solid black;\r\n");
      out.write("\tbackground:#333333;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tpadding:3px 8px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("tr td input.check{\r\n");
      out.write("\r\n");
      out.write("\tborder:1px solid black;\r\n");
      out.write("\tbackground:#333333;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tpadding:3px 8px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("tr td button.cancle{\r\n");
      out.write("\r\n");
      out.write("\tborder:1px solid red;\r\n");
      out.write("\tbackground:red;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tpadding:3px 8px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("border:none;\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function check(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar pw1 = document.getElementById(\"pw\").value;\r\n");
      out.write("\tvar pw2 = document.getElementById(\"pw2\").value;\r\n");
      out.write("\t\r\n");
      out.write("\tif(f.id.value==\"\"){\r\n");
      out.write("\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\tf.id.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(f.pw.value==\"\"){\r\n");
      out.write("\t\talert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\tf.pw.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(pw2==\"\"){\r\n");
      out.write("\t\talert(\"확인 비밀번호를 입력해주세요\")\r\n");
      out.write("\t\tf.pw2.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(pw2 != pw1){\r\n");
      out.write("\t\talert(\"동일한 비밀번호를 입력해 주세요\")\r\n");
      out.write("\t\tf.pw2.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(f.nick.value==\"\"){\r\n");
      out.write("\t\talert(\"닉네임을 입력해주세요\")\r\n");
      out.write("\t\tf.nick.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(f.name.value==\"\"){\r\n");
      out.write("\t\talert(\"이름을 입력해주세요\");\r\n");
      out.write("\t\tf.name.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(f.email.value==\"\"){\r\n");
      out.write("\t\talert(\"이메일을 입력해주세요\");\r\n");
      out.write("\t\tf.email.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(f.hint.value==\"\"){\r\n");
      out.write("\t\talert(\"비밀번호를 찾을시 이용되는 힌트를 입력해주세요\");\r\n");
      out.write("\t\tf.hint.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function idCheck(input){\r\n");
      out.write("\t\r\n");
      out.write("\tvar url =\"member/idCheck.jsp?id=\"+input.id.value;\r\n");
      out.write("\twindow.open(url,\"chkForm\",\"width=500, height=300, resizable = no,scrollbar =no\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pwCheck(){\r\n");
      out.write("\t\r\n");
      out.write("\tif(f.pw.value == f.pw2.value){\r\n");
      out.write("\t\tdocument.getElementById(\"pw2_text\").innerHTML = \"\";\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tdocument.getElementById(\"pw2_text\").innerHTML = \"<p><font color='black'>비밀번호가 일치하지 않습니다</font><p>\"\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br><br><br><br><br><br><br>\r\n");
      out.write("<form name =\"f\" action=\"join.do\" method=\"post\" onSubmit=\"return check()\">\r\n");
      out.write("<table>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <th colspan=2 style=\"padding-left:130px;\">\r\n");
      out.write(" <a href=\"mainPage.do\">\r\n");
      out.write(" \t<font class=\"logo\" color=\"red\" size=\"32pt\">You</font>\r\n");
      out.write("\t\t\t<font class=\"logo\" color=\"black\" size=\"32pt\">Sub</font>\r\n");
      out.write(" </a>\r\n");
      out.write(" </th>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr> \r\n");
      out.write(" <td><font class=logo>Member ID</font></td>\r\n");
      out.write(" <td>:<input type=text name=\"id\" placeholder=\"아이디를 입력해주세요.\" size=30></td>\r\n");
      out.write(" <td><input type=\"button\" value=\"ID중복검사\" onClick=\"idCheck(this.form)\" class=\"check\">\r\n");
      out.write(" <input type=hidden name=\"idChecked\" value=\"idUncheck\"></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td><font class=logo>PASSWORD</font></td>\r\n");
      out.write(" <td colspan=2>:<input type=\"password\" name=\"pw\" placeholder=\"비밀번호를 입력해주세요.\" size=30 id=\"pw\" ></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td><font class=logo>PW CHECK</font></td>\r\n");
      out.write(" <td>:<input type=\"password\" name=\"pw2\" placeholder=\"비밀번호를 한번더 입력해주세요.\" size=30 id=\"pw2\" onchange=\"pwCheck()\"></td>\r\n");
      out.write(" \r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr>\r\n");
      out.write(" \t<td><font class=\"logo\">NickName</font></td>\r\n");
      out.write(" \t<td>:<input type=\"text\" name=\"nick\" placeholder=\"별명을 입력해주세요.\" size=30></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" \t<td><font class=\"logo\">Name</font></td>\r\n");
      out.write(" \t<td>:<input type=\"text\" name=\"name\" placeholder=\"이름을 입력해주세요.\" size=30></td>\r\n");
      out.write(" </tr>\r\n");
      out.write("\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td><font class=\"logo\">E-Mail</font></td>\r\n");
      out.write(" <td>:<input type=\"email\" name=\"email\" placeholder=\"이메일을 입력해주세요.\" size=30 ></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr> \r\n");
      out.write("\t<td class=\"logo\">PW Hint</td>\r\n");
      out.write("\t<td>:<input type=\"text\" name=\"pwhint\" placeholder=\"본인만 아는 힌트를 입력해주세요.\" size=30></td>\r\n");
      out.write("</tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td id=\"pw2_text\" colspan=\"3\" align=\"center\" style=\"background-color:rgba(255,0,0,0.7);\"></td>\r\n");
      out.write(" </tr>\r\n");
      out.write("\r\n");
      out.write(" <tr>\r\n");
      out.write("\r\n");
      out.write(" <td align=\"center\">\r\n");
      out.write(" </td>\r\n");
      out.write(" <td align=\"center\">\r\n");
      out.write(" <button type=\"submit\" class=\"sign\">회원가입</button>\r\n");
      out.write(" <button type=\"button\" class=\"cancle\"><a href=\"loginPage.do\" style=\"text-decoration: none; color:black\">취 소</a></button>\r\n");
      out.write(" </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <p id=\"ptag\"></p>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
