/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2019-10-16 12:40:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\r\n");
      out.write("<meta name=\"viewport\" content=\"user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap.css\">\r\n");
      out.write("<title>YouSub LOG IN 페이지</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Righteous&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Gothic+A1|Righteous&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".logo{\r\n");
      out.write("text-align:center;\r\n");
      out.write("font-family:righteous,serif;\r\n");
      out.write("}\r\n");
      out.write(".kor{\r\n");
      out.write("font-family:\"Gothic A1\",serif;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("margin-left:auto;\r\n");
      out.write("margin-right:auto;\r\n");
      out.write("margin-top:auto;\r\n");
      out.write("margin-botton:auto;\r\n");
      out.write("text-align: center;\r\n");
      out.write("}\r\n");
      out.write("logocl{\r\n");
      out.write("padding-top:100px\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function check(){\r\n");
      out.write("\t\r\n");
      out.write("\tif(f.id.value==\"\"){\r\n");
      out.write("\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\tf.id.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(f.pw.value==\"\"){\r\n");
      out.write("\t\talert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\tf.pw.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("<form action=\"logIn.do\" method=post name=\"f\" onSubmit=\"return check()\">\r\n");
      out.write("\t<table >\r\n");
      out.write("\t\t<tr class=logocl  >\r\n");
      out.write("\t\t\t<th colspan=2 style=\"padding-left: 19%\">\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"mainPage.do\">\r\n");
      out.write("\t\t\t\t\t<font class=\"logo\" color=\"red\" size=\"15px\" >You</font>\r\n");
      out.write("\t\t\t\t\t<font class=\"logo\" color=\"black\" size=\"15px\">Sub</font>\r\n");
      out.write("\t\t\t\t</a> \r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td><font class=logo >ID</font></td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"id\" id=\"id\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td><font class=logo>PASSWORD</font></td>\r\n");
      out.write("\t\t<td><input type=\"password\" name=\"pw\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=2 align=\"center\" ><input type=submit value=\"LOG IN\" class=\"btn btn-black\" style=\"padding: 10px; padding-left:104px; padding-right: 104px; background-color:black; color:white;\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" bgcolor=\"white\" height=\"3px\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=2><a href=\"joinPage.do\" style=\"color:black; padding: 10px; padding-left:95px; padding-right: 95px; background-color:red; color:white;\" class=\"btn\" >회원가입</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=2></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</form>\r\n");
      out.write("<table align=\"center\"><tr><td>\r\n");
      out.write("\t<a id=\"kakao-login-btn\"></a>\r\n");
      out.write("<a href=\"http://developers.kakao.com/logout\"></a>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//<![CDATA[\r\n");
      out.write("//사용할 앱의 JavaScript 키를 설정해 주세요.\r\n");
      out.write("\tKakao.init('ec21d68c0494757474bc8fa4b1ff2ef8');\r\n");
      out.write("//카카오 로그인 버튼을 생성합니다.\r\n");
      out.write("\tKakao.Auth.createLoginButton({\r\n");
      out.write("\t\tcontainer: '#kakao-login-btn',\r\n");
      out.write("\t\tsuccess: function(authObj) {\r\n");
      out.write("\t\t alert(JSON.stringify(authObj));\r\n");
      out.write("\t\t },\r\n");
      out.write("\t\t fail: function(err) {\r\n");
      out.write("  \t\talert(JSON.stringify(err));\r\n");
      out.write("\t\t }\r\n");
      out.write("\t});\r\n");
      out.write("//]]>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
