/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2019-10-16 14:36:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.yousub.DTO.*;

public final class offer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Righteous&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Gothic+A1|Righteous&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/bootstrap.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main_top.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main_menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<table border='0' width='1000' cellspacing='0' cellpadding='2'\r\n");
      out.write("\t\t\talign=center>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th><h1>추천튜브</h1></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr bgcolor=\"black\" height=30>\r\n");
      out.write("\t\t\t\t<td width=150px><font color=\"white\" class=font>&nbsp;&nbsp;추천채널</font></td>\r\n");
      out.write("\t\t\t\t<td style=\" text-align: center\" width=550px ><font color=\"white\" class=font>추천내용</font></td>\r\n");
      out.write("\t\t\t\t<td width=100><font color=\"white\" class=font>&nbsp;&nbsp;닉네임</font></td>\r\n");
      out.write("\t\t\t\t<td width=100><font color=\"white\" class=font>&nbsp;&nbsp;작성일</font></td>\r\n");
      out.write("\t\t\t\t<td width=100><font color=\"white\" class=font>&nbsp;&nbsp;조회수</font></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=5 height=\"2\" bgcolor=\"red\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
 ArrayList<OfferDTO> offerList = (ArrayList<OfferDTO>) request.getAttribute("offerList"); 
				
				int where = 1;
				
				int totalgroup =0;
				int maxpages=10;
				int startpage = 1;
				int endpage = startpage + maxpages - 1;
				int wheregroup = 1;
				if(request.getParameter("ogo") !=null){
					where = Integer.parseInt(request.getParameter("ogo"));
					
					wheregroup = (where -1) / maxpages +1;
					
					startpage = (wheregroup - 1) * maxpages +1;
					
					endpage = startpage + maxpages - 1;
					
				}else if(request.getParameter("ogogroup") != null){
					wheregroup = Integer.parseInt(request.getParameter("ogogroup"));
					
					startpage = (wheregroup -1)*maxpages+1;
					endpage = startpage+ maxpages -1;
					
					where = startpage;
				}
			
				int nextgroup = wheregroup +1;
				int priorgroup = wheregroup -1;
				
				int nextpage = where +1;
				int priorpage = where -1;
				
				int startrow = 0;
				int endrow = 0;
				
				int maxrows = 15;
				int totalrows = 0;
				int totalpages = 0;
				
				if(offerList.size() > 0){
					totalrows = offerList.size();
					totalpages = (totalrows-1) / maxrows +1;
					startrow = (where -1)*maxrows;
					endrow = startrow +maxrows-1;
					
					if(endrow >= totalrows){
						endrow = totalrows -1;
					}
					
					totalgroup = (totalpages-1)/maxpages+1;
					
					if(endpage > totalpages){
						endpage = totalpages;
					}
				}
				
				for(int i = startrow;i<endrow;i++){
					if(i%2 == 0){
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr bgcolor=\"white\" height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=150px><font color=\"white\" class=font>&nbsp;&nbsp;");
      out.print(offerList.get(i).getoTitle() );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\" text-align: center\" width=550px ><font color=\"white\" class=font>");
      out.print(offerList.get(i).getoContent() );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=100><font color=\"white\" class=font>&nbsp;&nbsp;");
      out.print(offerList.get(i).getNick() );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=100><font color=\"white\" class=font>&nbsp;&nbsp;");
      out.print(offerList.get(i).getoDate() );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=100><font color=\"white\" class=font>&nbsp;&nbsp;조회수");
      out.print(offerList.get(i).getoHit() );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");
			
					}else{
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr bgcolor=\"lightgrey\" height=30>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=150px><font color=\"white\" class=font>&nbsp;&nbsp;");
      out.print(offerList.get(i).getoTitle() );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\" text-align: center\" width=550px ><font color=\"white\" class=font>");
      out.print(offerList.get(i).getoContent() );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=100><font color=\"white\" class=font>&nbsp;&nbsp;");
      out.print(offerList.get(i).getNick() );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=100><font color=\"white\" class=font>&nbsp;&nbsp;");
      out.print(offerList.get(i).getoDate() );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=100><font color=\"white\" class=font>&nbsp;&nbsp;조회수");
      out.print(offerList.get(i).getoHit() );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");
			
					}
				}
			
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=5 height=\"2\" bgcolor=\"red\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=5 height=\"4\" bgcolor=\"white\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
 if(session.getAttribute("id") !=null){
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=4></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"button\" value=\"채널 추천하기\" onClick=\"location.href='offerWritePage.do'\" class=\"btn btn_black\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");

			}
			
      out.write("\r\n");
      out.write("\t\t\t<tr align=center>\r\n");
      out.write("\t\t\t\t<td colspan=5><input type=text style=\"border:1px solid lightgrey \">&nbsp;&nbsp;<input type=\"button\" onclick=\"location.href='offerSearch.do'\" value=\"검색\" class=\"btn btn_danger\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t");

					if(wheregroup>1){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"offerPage.do?ogo=1\">처음</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"offerPage.do?ogogroup=");
      out.print(priorgroup );
      out.write("\">이전&nbsp;</a>\r\n");
      out.write("\t\t\t\t\t\t");

					}else{
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t처음&nbsp;이전&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");

					}
				
				for(int jj = startpage; jj<=endpage; jj++){
					if(jj ==where){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<strong>");
      out.print(jj );
      out.write("</strong>\r\n");
      out.write("\t\t\t\t\t");

					}else{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"offerPage.do?go=");
      out.print(jj );
      out.write("\">&nbsp;");
      out.print(jj );
      out.write("&nbsp;</a>\r\n");
      out.write("\t\t\t\t\t");
	
					}
				}
				
				if(wheregroup< totalgroup){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t&nbsp;<a href=\"offerPage.do?ogogroup=");
      out.print(nextgroup );
      out.write("\">다음</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"offerPage.do?=ogogroup=");
      out.print(totalgroup );
      out.write("\">마지막</a>\r\n");
      out.write("\t\t\t\t\t");

					
				}else{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t&nbsp;다음&nbsp;마지막\r\n");
      out.write("\t\t\t\t\t");

				}
				
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /board/offer.jsp(48,3) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offerList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /board/offer.jsp(48,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("offerList");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offerList.offerId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offerList.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offerList.nick }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offerList.oDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offerList.oHit}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t</tr>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
